config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy]
  end

  root to: 'pages#home'

  resources :recipes do
    member do
      get :mark_done
    end
    resources :reviews, only: %i[new create edit update]
    resources :recipe_items
  end
  resources :planned_recipes, only: [:create, :index, :edit, :update, :show] do
    collection do
      post :planner
      get :planner
      get :shopping_list
    end
    member do
      get :steal
      post :steal
    end
  end
  resources :fridge_items, path: "my_fridge", only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get :add
    end
  end
  resources :posts, only: [:index, :new, :create] do
    resources :comments, only: [:create]
  end
end

app/models/planned_recipe.rb
class PlannedRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :date, uniqueness: true, allow_nil: true
end

app/controllers/planned_recipes_controller.rb
class PlannedRecipesController < ApplicationController
  before_action :find_planned_recipe, only: %i[show edit update]
  skip_before_action :verify_authenticity_token

  def index
    @planned_recipes = PlannedRecipe.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @planned_recipe = PlannedRecipe.new
  end

  def create
    @planned_recipe = PlannedRecipe.new(planned_recipe_params)
    @planned_recipe.user_id = current_user.id
    if @planned_recipe.save
      redirect_to planned_recipes_path(@planned_recipe)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @planned_recipe.update(planned_recipe_params)
    redirect_to planned_recipes_path(@planned_recipe)
  end

  def planner
    days = params[:days]
    @planner_recipes = PlannedRecipe.where.not(date: nil).order(:date)
    @future_meals = @planner_recipes.select { |meal| meal.date > Date.today }
    today = @future_meals.count < 1 ? Date.today : PlannedRecipe.where.not(date: nil).order(:date).last.date
    i = 1
    days.to_i.times do
      PlannedRecipe.create!(date: today + i, user: current_user, recipe: Recipe.last)
      today += 1.day
    end
    @planner_recipes = PlannedRecipe.where.not(date: nil).order(:date)
    @all_recipes = Recipe.where(creator: current_user)
    @future_meals = @planner_recipes.select { |meal| meal.date > Date.today }
  end

  def shopping_list
    @meals = PlannedRecipe.where.not(date: nil).all.select{ |meal| meal.date > Date.today }
    shopping_list = {}
    @meals.each do |meal|
      meal.recipe.recipe_items.each do |item|
        if shopping_list.has_key?(item.ingredient.name)
          shopping_list[item.ingredient.name] += item.quantity
        else
          shopping_list[item.ingredient.name] = item.quantity
        end
      end
    end
    @shopping_list = shopping_list
    @fridge_items = {}
    FridgeItem.all.select{ |item| item.user = current_user }.each do |item|
      @fridge_items[item.ingredient.name] = item.quantity
    end
    @shopping_list.each do |shopping, _vol|
      if @fridge_items.has_key?(shopping)
        @shopping_list[shopping] -= @fridge_items[shopping]
      end
    end
    return @shopping_list
  end

  def steal
    @planned_recipe = PlannedRecipe.new(recipe_id: params[:id])
    recipe = Recipe.find(params[:id].to_i)
    @planned_recipe.user_id = current_user.id
    if @planned_recipe.save!
      redirect_to recipes_path(recipe)
    end
  end

  private

  def find_planned_recipe
    @planned_recipe = PlannedRecipe.find(params[:id])
  end

  def planned_recipe_params
    params.require(:planned_recipe).permit(:date, :recipe_id)
  end
end

app/views/planned_recipes/planner.html.erb
<div class="pages-header">
<h2 class="text-center mb-5 page-title">My Planner</h2>
</div>

<div class="">
  <div class="content-planner">
    <div class="planner-card">
      <% @planner_recipes.each do |recipe| %>
        <% if recipe.date > Date.today %>
        <div class="planner-day mb-3" data-controller="planner-day">
          <% @planned_recipe = PlannedRecipe.find(recipe.id) %>
          <p class="date-planner p-2"><%= recipe.date.strftime("%A, %b %d") %></p>
          <%= simple_form_for @planned_recipe, method: :patch, html: { data: { planner_day_target: 'form', action: 'change->planner-day#submitForm' }} do |f| %>
            <%= f.association :recipe, collection: Recipe.where(creator: current_user) + PlannedRecipe.where(user: current_user).where(date: nil).map { |r| r.recipe }, label: false, include_blank: true %>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>

<% if @future_meals.count > 0 %>
  <div class="closingbar"></div>
  <div class="text-center text-small">
    <small><%= link_to "Generate Shopping list", shopping_list_planned_recipes_path, class: "btn-myplanner general-button-blue text-white" %>
    <br>
    <button type="button" class="btn-myplanner general-button-green text-white" data-toggle="modal" data-target="#exampleModal">
      Add days
    <small></button>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">How many days?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="/planned_recipes/planner" method="post" class="recipe-form-home mt-2">
            <div><input type="integer" name="days" class="search-bar-home mb-1 px-5 py-2 text-center lead" placeholder="e.g. 5"></div>
            <div class="text-center"><input type="submit", class="btn-myplanner general-button-blue text-white"></div>
          </form>
        </div>
      </div>
    </div>
  </div>


    </div>
  <% else %>
    <div class="mb-4 text-center mx-5"><h4 class="text-center align-items-start">How many meals would you like to plan?</h4></div>
    <form action="/planned_recipes/planner" method="post" class="recipe-form-home mt-2 mx-3">
      <div class="container">
        <div><input type="integer" name="days" class="search-bar-home mb-1 px-5 py-2 text-small text-center" placeholder="e.g. 5"></div>
        <div class="text-center"><input value="Go!", type="submit", class="general-button-blue"></div>
      </div>
    </form>
  <% end %>
</div>

app/views/planned_recipes/shopping_list.html.erb
<div class="pages-header">
  <h2 class="text-center mb-5 page-title">Shopping List</h2>
</div>


<div class="container mt-5">
  <div class="d-flex flex-column mt-3 mx-3" data-controller="shopping-list">
    <% @shopping_list.each do |shopping, num| %>
      <% if num > 0 %>
      <% @fridge_item = FridgeItem.new %>
        <div id="shopping-row" class="row d-flex justify-content-between my-1" data-shopping-list-target="item">
          <div class="d-inline w-100 ml-2">
            <%= shopping %>
          </div>
          <div class="d-inline text-right">
            <%= form_for @fridge_item, url: add_fridge_item_path(shopping), method: :get do |f| %>
              <%= f.text_field :quantity, as: :integer, class: 'mt-0 w-25', value: num, placeholder: num %>
              <span class="inline mr-2"><%= Ingredient.where(name:shopping).first.unit unless Ingredient.where(name:shopping).first.unit == "number" %></span>
              <%= button_tag class: 'border-none align-middle', type: 'submit' do %>
                 <p class="btn-shoppinglist general-button-blue text-white mb-0 mr-0">Add to fridge<p>
                <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="closingbar"></div>

<div class="button-show d-flex flex-column justify-content-around">
  <%= link_to "Back", recipes_path(@recipes), class: "btn btn-showpage" %>
</div>