config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy]
  end

  root to: 'pages#home'

  resources :recipes do
    member do
      get :mark_done
    end
    resources :reviews, only: %i[new create edit update]
    resources :recipe_items
  end
  resources :planned_recipes, only: [:create, :index, :edit, :update, :show] do
    collection do
      post :planner
      get :planner
      get :shopping_list
    end
    member do
      get :steal
      post :steal
    end
  end
  resources :fridge_items, path: "my_fridge", only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get :add
    end
  end
  resources :posts, only: [:index, :new, :create] do
    resources :comments, only: [:create]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_one_attached :photo
  has_many :recipe_items, dependent: :destroy
  has_many :planned_recipes, dependent: :destroy
  has_many :reviews
  has_many :ingredients, through: :recipe_items

  validates :creator, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :instructions, presence: true
  validates :cooking_time, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    associated_against: {
      ingredients: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: %i[show edit update destroy mark_done]

  def index
    my_recipes
    if params[:query].present?
      @recipes = Recipe.search_by_name_and_description(params[:query])
    else
      if @user_recipes.count < 3
        @recipes = Recipe.all
      else
        @recipes = @user_recipes
      end
    end
  end

  def my_recipes
    @my_recipes = Recipe.where(creator: current_user)
    @stolen_recipes = PlannedRecipe.where(user: current_user)
    @stolen_recipes = @stolen_recipes.select {|r| r.date == nil }
    @friend_recipes = []
    @stolen_recipes.each do |recipe|
      @friend_recipes << recipe.recipe
    end
    @user_recipes = @my_recipes + @friend_recipes
  end

  def show
    @review = Review.new
    @reviews = @recipe.reviews
    total_rating = 0
    count = 0
    @recipe.reviews.each do |review|
      total_rating += review.rating
      count += 1
    end
    @average_rating = total_rating/count if count > 0
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.creator = current_user
    params["recipe"]["ingredient_ids"][1..-1].each do |id|
      if @recipe.ingredients.empty?
        recipe_item = RecipeItem.new
        recipe_item.ingredient = Ingredient.find_by_id(id)
        recipe_item.recipe = @recipe
        recipe_item.quantity = 1
        recipe_item.save
      else
        recipe_item = RecipeItem.new
        recipe_item.ingredient = Ingredient.find_by_id(id)
        recipe_item.recipe = @recipe
        recipe_item.quantity = 1
        recipe_item.save
      end
    end
    if @recipe.save
      redirect_to recipes_path(@recipe)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path(@recipe)
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path(@recipe)
  end

  def mark_done
    items = @recipe.recipe_items.load_target
    fridge_hash
    items.each do |item|
      if @fridge_items.has_key?(item.ingredient.name)
        fridge_item = FridgeItem.where(ingredient_id: item.ingredient_id).first
        new_amount = fridge_item.quantity -= item.quantity
        if new_amount < 1
          fridge_item.destroy
        else
          fridge_item.update!(quantity: new_amount)
        end
      end
    end
    redirect_to recipe_path(@recipe)
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :instructions, :cooking_time, :description, :photo, :ingredient_ids)
  end

  def fridge_hash
    @fridge_items = {}
    FridgeItem.all.select{ |item| item.user = current_user }.each do |item|
      @fridge_items[item.ingredient.name] = 1
    end
  end
end

app/views/recipes/_form.html.erb
<div class="addrecipeform">
  <div class="container text-center">
    <%= simple_form_for(@recipe) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :instructions %>
      <%= f.association :ingredients, collection: Ingredient.all, input_html: {multiple: true, data: { controller: 'select2' }} %>
      <%= f.input :cooking_time %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "add recipe", class: "general-button-blue mt-4" %>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="banner-recipe mt-3 text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.cnn.com/cnnnext/dam/assets/201117152746-cookgiftslead-live-video.jpg);">
  <div class="container">
    <h2 class="text-white text-lobster">Add your own recipe</h2>
    <br>
    <%= link_to "Add Recipe", new_recipe_path, class: "general-button-green text-white" %>
  </div>
</div>

<div class="bg-color-search-recipe">
  <div class="d-flex flex-column align-items-center text-center">
    <div class="search-container-recipe d-flex flex-column" id="search-recipe-index">
      <h2 class="text-lobster">Or find recipes you saved</h2>
        <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Ingredient or recipe name"
          %>
          <%= submit_tag "Search", class: "general-button-blue mb-3" %>
        <% end %>
    </div>
  </div>
</div>


<div class="content">
<br><br>
  <div class="cards">
  <% @recipes.each do |recipe| %>
    <div class="recipe-card" data-aos="fade-up" data-aos-anchor-placement="top-center" data-aos-offset="-220" data-aos-duration="1000">
    <% total_rating = 0 %>
    <% count = 0 %>
    <% recipe.reviews.each do |review| %>
      <% total_rating += review.rating %>
      <% count += 1 %>
    <% end %>
    <% average_rating = total_rating/count if count > 0 %>
    <% average_rating.to_i %>

      <%= link_to "", recipe_path(recipe), class: "stretched-link" %>
      <%= cl_image_tag recipe.photo.key, class: "rounded index-img", width: "100%", height: '200px', alt: "an image of a recipe" %>
      <h5 class="card-title pt-4 text-center">🥘 <%= recipe.name %></h5>
      <h6 class="p-4 text-center"><%= recipe.description.split('.').first %></h6>
      <p class="card-text text-center">Creator🧑‍🍳 <%= recipe.creator.username %></p>
      <p class="card-text text-center pb-4">⏰ <%= recipe.cooking_time %> mins</p>
      <p class="card-text text-center pb-4">
      Average Rating:
      <% if count > 0 %>
        <% average_rating.to_i.times do %>
          <i class="fas fa-star"></i>
        <% end %>
      <% else %>
        No ratings
      <% end %>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="show-page-container">
  <div class="banner-show"></div>
  <div class="img-holder">
    <%= cl_image_tag @recipe.photo.key, class: "show-img center", width: "100%", height: '200px', alt: "an image of a recipe" %>
    <% unless current_user == @recipe.creator %>
      <%= link_to "Add recipe!", steal_planned_recipe_path(@recipe), method: :post, class: "add-rcp-btn btn-myplanner general-button-blue text-white" %>
    <% end %>
  </div>

    <div class="show-review d-flex flex-column pb-4">
      <h5 class="text-center my-5"><%= @recipe.name %></h5>
      <p class="text-center mb-5"><%= @recipe.description %></p>
    </div>
    <div class="show-review d-flex justify-content-between">
      <h6 class="pl-10">
        <% if @recipe.reviews.empty? %>
          Be the first to leave a rating
        <% else %>
          <strong>
            <% @average_rating.to_i.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          </strong>
          <%= link_to " (#{@recipe.reviews.count} #{@recipe.reviews.count > 1 ? "reviews" : "review"})", recipe_path(@recipe, anchor: "reviews"), class: "text-small" %>
        <% end %>
      </h6>
      <p><%= @recipe.cooking_time %>min</p>
    </div>

  <div class="container col-11 mx-auto">
    <div class="show-review-ing d-flex flex-column mt-3 mx-3">
        <h5 class="text-center pb-5" id="anchor-item">Ingredients</h5>
        <% @recipe.recipe_items.each do |item| %>
          <% if item.quantity > 0%>
          <div class="d-flex justify-content-left">
            <div class="mt-2">
              <p class="d-flex align-items-center" %><strong> <%= item.quantity %><%= item.ingredient.unit unless item.ingredient.unit == "number" %> x <%= item.ingredient.name %> </strong></p>
            </div>
            <div class="mt-0">
            <% if item.recipe.creator_id == current_user.id %>
              <button type="" class="btn btn-add-ingredient" data-toggle="modal" data-target=<%="#itemModal#{item.ingredient.name}"%> >
                ✏️
              </button>
            <% else %>
              <%= "" %>
            <% end %>
            </div>
          </div>
          <% end %>
        <% end  %>
    </div>
  </div>

    <div class="show-review-ing d-flex flex-column">
      <h5 class="text-center my-3">Instructions</h5>
      <p class="text-center mt-3 mb-10" id="instructions"><%= @recipe.instructions %></p>
    </div>

    <div id="reviews">
      <div class="show-review-ing d-flex flex-column">
        <% if @recipe.reviews.blank? %>
          <p>Be the first to <span data-toggle="modal" data-target="#exampleModal"><strong>leave a review</strong></span> for <%= @recipe.name %> !</p>
        <% else %>
          <% @recipe.reviews.each do |review| %>
            <p> <%= review.user.username.capitalize %> said "<%= review.comment.capitalize %>"</p>
            <p><% review.rating.to_i.times do  %>
              <i class="fas fa-star"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Ingredient Modal -->

<% @recipe.recipe_items.each do |item| %>
  <div class="modal fade" id=<%="itemModal#{item.ingredient.name}"%> tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content text-center">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <% @recipe_item = item %>
          <%= simple_form_for [@recipe, @recipe_item], url: recipe_recipe_item_path(@recipe) , method: :patch do |f| %>
          <%= f.input :quantity, as: :integer %>
          <%= f.input :id, as: :hidden, input_html: {value: @recipe_item.id} %>
          <%= f.submit %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<!-- Review Modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@recipe, @review] do |f| %>
        <%= f.input :comment, as: :text %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate the recipe (5 if you love it!)" %>
        <%= f.submit "Send your review", class:"btn-myplanner general-button-blue text-white" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="button-show d-flex flex-column justify-content-around">
<span class="btn general-button-blue mb-3" data-toggle="modal" data-target="#exampleModal">Leave a review</span>
  <%= link_to "Mark as cooked!", mark_done_recipe_path(@recipe), class: "btn general-button-green mb-3" %>
  <%= link_to "Back", recipes_path(@recipes), class: "btn btn-showpage" %>
</div>