config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy]
  end

  root to: 'pages#home'

  resources :recipes do
    member do
      get :mark_done
    end
    resources :reviews, only: %i[new create edit update]
    resources :recipe_items
  end
  resources :planned_recipes, only: [:create, :index, :edit, :update, :show] do
    collection do
      post :planner
      get :planner
      get :shopping_list
    end
    member do
      get :steal
      post :steal
    end
  end
  resources :fridge_items, path: "my_fridge", only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get :add
    end
  end
  resources :posts, only: [:index, :new, :create] do
    resources :comments, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy, foreign_key: :creator
  has_many :fridge_items, dependent: :destroy
  has_many :friend_requests, dependent: :destroy, foreign_key: :requester
  has_many :planned_recipes, dependent: :destroy
  has_many :users, through: :friend_requests

  has_one_attached :photo
  has_many :reviews

  include PgSearch::Model
  pg_search_scope :search_by_email,
    against: [ :email ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search_by_email(params[:query])
    @following = current_user.friend_requests
  end
end

app/views/users/index.html.erb
<div class="pages-header">
  <h2 class="text-center mb-5 page-title">You currently follow:</h2>
</div>

<div class="container col-11 mx-auto mt-5">
  <% @following.each do |friend| %>
    <div class="friend-card">
      <%= cl_image_tag friend.recipient.photo.key, class: "avatar-sm", alt: "user_image" %>
      <%= friend.recipient.username %>
      <%= link_to user_friend_request_path(current_user, friend.id), method: :delete do %>
        <i class="fas fa-user-minus"></i>
      <% end %>
    </div>
  <% end %>

  <div class="pb-0 pt-1 pb-5 mt-4 text-center">
    <%= form_tag users_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a new sous-chef"
      %>
      <%= submit_tag "Search", class: "general-button-blue" %>
    <% end %>
  </div>
  <ul>
  <% @users.each do |user| %>
    <li><%= cl_image_tag user.photo.key, class: "avatar", alt: "user_image" %>
    <%= user.email %>
    <% @friends = [] %>
    <% @friends = @following.target.map { |link| link.recipient } %>
    <% if @friends.include?(user) %>
      <i class="fas fa-user-friends"></i>
    <% else %>
      <%= link_to user_friend_requests_path(user), method: :post do %>
        <i class="fas fa-user-plus"></i>
      <% end %>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>