config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy]
  end

  root to: 'pages#home'

  resources :recipes do
    member do
      get :mark_done
    end
    resources :reviews, only: %i[new create edit update]
    resources :recipe_items
  end
  resources :planned_recipes, only: [:create, :index, :edit, :update, :show] do
    collection do
      post :planner
      get :planner
      get :shopping_list
    end
    member do
      get :steal
      post :steal
    end
  end
  resources :fridge_items, path: "my_fridge", only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get :add
    end
  end
  resources :posts, only: [:index, :new, :create] do
    resources :comments, only: [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Souschef - Makes You Chef</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link href="https://www.dafontfree.net/embed/aGFybG93LXNvbGlkLXBsYWluJmRhdGEvNDcvaC81NjMwNi9IYXJsb3dTb2xpZFBsYWluLm90Zg" rel="stylesheet" type="text/css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="manifest" href="souschef.webmanifest">

  </head>

  <body>
  <div class="header-block">
    <div class="pos-f-t mb-4">
      <nav class="navbar navbar-souschef p-4">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="fas fa-bars"></i></span>
        </button>
        <h4 class="text-black page-title" id="text-logo"><%= link_to "Sous Chef", root_path %></h4>
      </nav>
      <div class="navbar-collapse collapse" id="navbarToggleExternalContent">
        <div class="bg-nav-collpse">
          <ul class="text-center">
            <li class="text-muted"><%= link_to 'Home', root_path %></li>
            <li class="text-muted"><%= link_to 'My Fridge', fridge_items_path %></li>
            <li class="text-muted"><%= link_to 'My Recipes', recipes_path %></li>
            <li class="text-muted"><%= link_to 'My Planner', planner_planned_recipes_path %></li>
            <li class="text-muted"><%= link_to 'My Shopping List', shopping_list_planned_recipes_path %></li>
            <li class="text-muted"><%= link_to 'My Friends', users_path %></li>
            <li class="text-muted pb-3"><%= link_to 'My News Feed', posts_path %></li>
            <li class="text-muted pt-3 pb-3"><%= link_to (image_tag("nonamelogo.png", alt:"SousChef", style:"width: 150px")), root_path%></li>
            <% if current_user %>
              <li class="text-muted logoutbtn"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="text-muted logoutbtn"><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

    <div class="container w-100 p-0 background">
      <%= yield %>
    </div>

    <br>
    <br>
    <br>
    <br>
    <%# <div class="footer" id="footerhome">
      <div class="footer-links">
        Coming soon...
      </div>
      <div class="footer-copyright">
          <%= link_to (image_tag("nonamelogo.png", alt:"SousChef", style:"width: 60px")), root_path%>
      <%# </div>
    </div> %>

  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script> AOS.init(); </script>

  </body>
</html>